version: '3'

services:
  app:
    container_name: api-node
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
      - PORT=3001
    ports:
      - 3001:3001
